-- we don't know how to generate root <with-no-name> (class Root) :(

comment on database postgres is 'default administrative connection database';

grant connect, create, temporary on database farm_vet_test to farmvet_user;

create table phinxlog
(
    version        bigint                not null
        primary key,
    migration_name varchar(100),
    start_time     timestamp,
    end_time       timestamp,
    breakpoint     boolean default false not null
);

alter table phinxlog
    owner to postgres;

create table fornecedor
(
    fornecedor_id integer generated by default as identity
        primary key,
    nome          varchar(255) not null,
    telefone      varchar(255),
    cnpj          varchar(255) not null,
    email         varchar(255)
);

alter table fornecedor
    owner to postgres;

create unique index "UNIQUE_EMAIL"
    on fornecedor (email);

create unique index "UNIQUE_CNPJ"
    on fornecedor (cnpj);

create unique index "UNIQUE_TELEFONE"
    on fornecedor (telefone);

create index "BY_NOME"
    on fornecedor (nome);

create table item
(
    id                     integer generated by default as identity
        primary key,
    nome                   varchar(255)                                              not null,
    tipo_item              varchar(255) default 'medicamento_vet'::character varying not null,
    estoque_minimo         integer                                                   not null,
    is_ativo               boolean      default true,
    is_controlado          boolean      default false,
    descricao_completa     text,
    descricao_complementar varchar(255),
    unidade                varchar(255)                                              not null,
    observacao             varchar(255),
    legislacao_especifica  varchar(255)
);

alter table item
    owner to postgres;

create table catmat
(
    codigo_catmat integer                             not null,
    data          timestamp default CURRENT_TIMESTAMP not null,
    item_id       integer                             not null
        references item
            on delete cascade,
    primary key (codigo_catmat, item_id, data)
);

comment on column catmat.item_id is 'Foreign key to items table';

alter table catmat
    owner to postgres;

create table lote
(
    id                  integer generated by default as identity
        primary key,
    data_vencimento     date         not null,
    data_de_recebimento date         not null,
    quantidade          integer      not null,
    valor_unitario      real         not null,
    valor_total         real,
    item_id             integer
                                     references item
                                         on update cascade on delete set null,
    numero_lote         varchar(255) not null,
    is_ativo            boolean      not null
);

alter table lote
    owner to postgres;

create table setor
(
    codigo varchar(255) not null
        primary key,
    nome   varchar(255) not null
);

alter table setor
    owner to postgres;

create table movimentacao
(
    id                     integer generated by default as identity
        primary key,
    data                   date        not null,
    setor_id               varchar(255)
        references setor
            on delete cascade,
    observacao             varchar(255),
    pessoa_requerente      varchar(255),
    requerimento           varchar(255),
    tipo_movimentacao      varchar(20) not null,
    nome_animal            varchar(255),
    ficha_clinica          varchar(255),
    log_lotes_movimentacao varchar(255),
    subtipo_movimentacao   varchar(20)
                                       references lote
                                           on update cascade on delete set null,
    fornecedor_id          integer
                                       references fornecedor
                                           on update cascade on delete set null,
    via_compra             varchar(255),
    documento_origem       varchar(255)
);

alter table movimentacao
    owner to postgres;

create table lote_movimentacao
(
    id              integer generated by default as identity
        primary key,
    lote_id         integer                             not null
        references lote
            on delete cascade,
    movimentacao_id integer                             not null
        references movimentacao
            on delete cascade,
    quantidade      integer                             not null,
    created         timestamp default CURRENT_TIMESTAMP not null,
    modified        timestamp
);

alter table lote_movimentacao
    owner to postgres;

